spring:
 application:
  name: s4-service
 datasource:
   url: jdbc:postgresql://localhost:5432/s4
   username: s4project
   password: s4project
 jpa:
  hibernate:
    ddl-auto: create-drop
  show-sql: true
  properties:
    hibernate:
      jdbc:
        lob:
          non_contextual_creation: true

server:
 port: 8088
 servlet:
  context-path: /restapi